### ISSUE TITLE
Chapters introduce concepts without explaining them

### ISSUE THREAD

**Issue by WallGeckoPoint** [rust-lang/rust-by-example#1042]
[Chapter 1.2 Formatted print](https://rustbyexample.com/hello/print.html?search=) introduces a Structure but tells us nothing about it, which is confusing (but mostly harmless at this point).

The chapter on [Debug](https://rustbyexample.com/hello/print/print_display.html) uses structures more, but also tells us confusingly very little about them. It includes at the end a syntax (`struct Person<'a> {`) which we know nothing about either.

This is still fairly harmless.

But then the chapter on [Display](https://rustbyexample.com/hello/print/print_display.html) launches into the concept of "implementing" and includes the `impl` keyword as well as function syntax (`fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result`)... which again we've learned nothing about up until this point.

What does `impl` do exactly? Why is it `for Structure`? What in blazes does `&self, f: &mut fmt::Formatter` mean...?

And I've only gotten that far :)

The basic issue is that in a "beginner tutorial," no concept should be "assumed obvious", **the reader should understand everything before we move on to something new, and we should understand that something new before moving on even further**.

Why is this important? Someone who's new will tend to leave if they get confused, and the easiest way to confuse someone is to toss in references to concepts they don't understand (yet)... without immediately resolving that lack of understanding.

**Comment by steveklabnik** [comment]
Hey @WallGeckoPoint ! A few things:

> The basic issue is that in a "beginner tutorial," no concept should be "assumed obvious", the reader should understand everything before we move on to something new, and we should understand that something new before moving on even further.

I agree that this is true, but this is actually literally impossible: features in Rust interact with each other in ways that you can't do this; you have to learn a bit, go onto a new thing, then go back to what you've learned to learn more advanced parts. That said, I think this is something important to strive for.

*that* being said, this was never originally intended as a "read it front to back and learn things" style doc, but more of a "Jump to the thing you care about and learn about it" doc. So that's also why you get this effect.

*that* being said, @frewsxcv and I have been talking about reorganizing the TOC to minimize these kinds of issues, and allow you to read things more front-to-back if you desire. So, we'll get there.

I'm going to leave this open for now, until we open that PR, as a reminder to CC you on it 😄

**Comment by WallGeckoPoint** [comment]
Thanks!

Temporary workaround: showed tutorial to a Rust programmer friend, who said "umm, yeah, that's not for beginners, just do The Book instead"... and it looks like indeed, The Book is much closer to what I was looking for / expecting.

The Book isn't perfect either, and it's probably not a good idea to just clone it (that would defeat the purpose of having multiple ways to learn Rust), but it may indeed be worth "taking a few pages" from its approach :)

**Comment by WallGeckoPoint** [comment]
Hmm, the more I think about this, the more I like the idea of cloning The Book's TOC... since if someone gets stuck on The Book they can go to the same chapter in RBE, and vice versa.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
