### ISSUE TITLE
Mutex chapter

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#105]
Come up with some examples of using Mutex and add them under https://rustbyexample.com/std.html

**Comment by brson** [comment]
No movement. If somebody adds Mutexes then so be it. Closing.

**Comment by brson** [comment]
Actually, I'm going to see if volunteers can be stirred up.

**Comment by brson** [comment]
Just come up with some examples of using `Mutex` and add them under the existing "Std misc" chapter. Perhaps once there's enough concurrency topics they can be broken out into a "Concurrency" chapter.

**Comment by phungleson** [comment]
@bors 

Concurrency is a big topic so it is a bit hard to think of where to start.

Perhaps if you have any suggestions where (books, sites, repos...) might have some ideas or patterns that are more related to rust's implementation of `Mutex` and `Arc`?

**Comment by brson** [comment]
@phungleson The [book chapter](https://doc.rust-lang.org/nightly/book/concurrency.html) is a good resource. I don't have any other docs related to Rust Mutex and Arcs offhand. Maybe it does make sense to cover them together since they are so often used together.

Topics I might expect examples to cover:

- Use Arcs to share immutable data across threads
- Use Arcs to share Mutexed mutable data across threads
- Use `lock` to get write access to interior data. Note that when the MutexGuard goes out of scope the lock is released
- Negative example: you can't access the mutable data when the lock is released
- When a thread panics while holding the lock is poisoned and subsequent locks will fail
- How to get around the poisoning and take the lock anyway.

**Comment by numberMumbler** [comment]
I'll start on this if it's still available (@phungleson?)

**Comment by phungleson** [comment]
Yep it's available

**Comment by brson** [comment]
Thanks @numberMumbler !

**Comment by steveklabnik** [comment]
It doesn't seem like @numberMumbler is working on this; if anyone else would like to, I'd be happy to help mentor!

**Comment by hardvain** [comment]
@steveklabnik I will write a chapter on Mutex, Rc, Arc together. I wanted to learn how rust handles this for quite sometime. Will start with this if this is still available.

**Comment by steveklabnik** [comment]
Absolutely!

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
