### ISSUE TITLE
std_misc/channels: not all threads report finished

### ISSUE THREAD

**Issue by yaymukund** [rust-lang/rust-by-example#1099]
I observe that not all threads always report finished. I asked about this in `#rust-beginners` and sarnold suggested it might be a race condition "since there's no explicit `join()` call to make sure all the threads terminate."

![threads-dont-log](https://user-images.githubusercontent.com/590450/44181667-c5099900-a0b7-11e8-85fc-e6de3586b554.gif)

**Comment by frewsxcv** [comment]
The `rx.recv()` call waits for all three messages to send from within the thread, so it'll wait for the thread in that regard. _But_, it's possible for the main thread to finish before the three child threads have finished printing, which is why we don't see all three prints sometimes. A couple options:

- Collect the thread handles, then call `join` on all of them, or
- Move the `print` before the `send` within the thread

**Comment by yaymukund** [comment]
@frewsxcv thanks for explaining— I learned a thing! 😄

I opted to use `join()`. The example already goes into how `send()` is a non-blocking operation so it feels natural to also demonstrate how to wait for threads.
