### ISSUE TITLE
Split the current "testing" chapter

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#111]
The current chapter needs to be split:
- [ ] intro: The `#[test]` attribute and `rustc --test`
- [ ] `#[should_fail]`
- [ ] conditional compilation: `#[test]` is kind of sugar for `#[cfg(test)]`
- [ ] FUT (function under test) have their stdout silenced by default, explain how to override this
- [ ] Disable tests using the `ignore` attribute
- [ ] Execute a subset of tests using regexes

---

@alxgnon is working on this

**Comment by steveklabnik** [comment]
I don't think @alxgnon is still working on this after a few years 😄 If someone else would like to pick up the torch, I'd be happy to mentor!

**Comment by serejkus** [comment]
I'd like to take on that.

I think that it would be nice to have a chapter on testing (say, chapter 20 and moving meta and the rest after it to +1).
* The intro is a table of chapter's contents + links to doc book about testing and to nursery about testing
* The first subchapter is about unit tests: `#[cfg(test)] mod tests { use super::*; /* some unit tests here */ }`. Things to note: the purpose of unit tests, `assert*!` macros, `#[ignore]` and `#[should_panic]`, ability to test private functions.
* The second subchapter is about doctests. Things no note: "hiding" some code lines, `?` + `try_main` instead of `unwrap()` in tests
* Third subchapter is about integration tests. Things to note: not forgetting to `extern` crate. I'm not sure that I understand how interactive examples should work in this case.
* Fourth subchapter is about dev-dependencies. I'm not sure whether it is a proper place, but it is definiteley tests-related

Looking for suggestions about improving this plan

**Comment by steveklabnik** [comment]
This sounds great!

For the `try_main` stuff, linking to https://rust-lang-nursery.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark is probably good :)

**Comment by marioidival** [comment]
I'm closed this issue because #953 was merged
