### ISSUE TITLE
Could the bound lifetime example be improved? 

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-by-example#1400]
I'm looking at the Lifetime Bounds example (https://doc.rust-lang.org/rust-by-example/scope/lifetime/lifetime_bounds.html) and I'm confused. 
The example obviously shows some of syntax for bounds and lifetimes, e.g. `T: Debug + 'a`.
This is perfect clear to me.
What I missing is an example which would show the difference between bounded lifetime and not bounded.
I tried some of ideas which I was able to think of, but they actually made me confused even more.
So this whole experiment force me to think that I'm missing something.. . 

```rust
#[derive(Debug)]
struct TwoRefsTwoDependantLifes<'a, 'b: 'a> {
    left: &'a str,
    right: &'b str,
}

/// works like i expect
fn two_refs_two_dependant_lifes_ok() {
    {
        let tr: TwoRefsTwoDependantLifes;
        let left = String::new();
        let right = String::new();
        tr = TwoRefsTwoDependantLifes { left: &left, right: &right };
        dbg!(&tr);
    }
}

/// works like i expect
fn two_refs_two_dependant_lifes_err() {
    let _tr: TwoRefsTwoDependantLifes;
    {
        let _left = String::new();
        let _right = String::new();
        // error, uncomment it here ..
        //_tr = TwoRefsTwoDependantLifes { left: &_left, right: &_right };
    }
    // .. and here
    //dbg!(&_tr);
}

/// works, but i expected a failure
fn two_refs_two_dependant_lifes_different() {
    let longer = String::new();
    {
        let tr: TwoRefsTwoDependantLifes;
        let shorter = String::new();
        // i thought that with this setup one of 2 below lines will fail, but it doesn't O_o
        tr = TwoRefsTwoDependantLifes { left: &longer, right: &shorter };
        //tr = TwoRefsTwoDependantLifes { left: &shorter, right: &longer };
        dbg!(&tr);
    }
}


```

To be clear, what I'm asking is minimal example where the use of bounded lifetime is required/recommended/whatever.

**Comment by ultimaweapon** [comment]
I also experienced similar problems. The document said `'a: 'b` mean `'a` must outlive `'b` but whenever I tried it is opposite.

**Comment by Mooninaut** [comment]
I'm also struggling with lifetime syntax. The basic principle I'm trying to keep in mind is "A referred to value (referent) must always outlive all references to it". Lifetime syntax does not do a good job indicating which is the referent in all cases.

Defining `a -> b` as "a refers to b", and `a <= b` as the equivalent statement "a has a shorter lifetime than b":

In `struct Ref<'a> { r: &'a i32 }`, r is the reference and an i32 is the referent. The relationship is `Ref.r -> some i32`, or equivalently `Ref <= Ref.r <= 'a <= some i32`.

In `struct Ref2<'a, 'b: 'a> { r0: &'a i32, r1: &'b i32}`, r0 and r1 are both references, and two i32s are the referents. The constraint on `'b` is `'a <= 'b`. However, that is not the only constraint. There are also `Ref2.r0 -> 'a` and `Ref2.r1 -> 'a` constraints, which are equivalent to `Ref2 <= 'a` and `Ref2 <= 'b`, making `'a <= 'b` irrelevant. Since both `'a` and `'b` must outlive `Ref2`, nothing you can do _directly_ with a valid `Ref2` will violate the constraint `'a <= 'b`.

This means there needs to be a better example with truly independent lifetimes.

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
