### ISSUE TITLE
Feature request: add i18n support

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-by-example#1520]
The current [rust by example ] only has english document.
But why not add more i18n translate document.

user can select their own language, like : France, De, Es, Jp, Zh, Kr, It

I would like to join and translate document into Zh [Simple Chinese]

**Comment by ericswpark** [comment]
@cnmade all translations for RBE is available here:

https://github.com/rust-lang/rust-by-example#translations-to-other-languages

The section also lists Chinese which might be what you're looking for?

**Comment by dalance** [comment]
Now [mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers) works fine with RBE because https://github.com/google/mdbook-i18n-helpers/issues/66 was fixed.
It is an internationalization plugin for mdbook which is used at [Comprehensive Rust 🦀](https://google.github.io/comprehensive-rust)

I think that translations can be merged into this repository by the plugin and provide language selector.
