### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by Abhicodes-crypto** [rust-lang/rust-by-example#1628]
I was reading about Box from here https://doc.rust-lang.org/stable/rust-by-example/std/box.html
There is the below code in code snippet :
```rust
    // box size == pointer size
    println!("Boxed point occupies {} bytes on the heap",
             mem::size_of_val(&boxed_point));
    println!("Boxed rectangle occupies {} bytes on the heap",
             mem::size_of_val(&boxed_rectangle));
    println!("Boxed box occupies {} bytes on the heap",
             mem::size_of_val(&box_in_a_box));
 ```
I increased the variables in Point struct and mades its size 40 bytes on stack but still the Box size is 8 bytes , so in this code . I think the statements should be Boxed point occupies {} bytes on the stack instead of the heap. Basically I am saying that Box is  holding an address value of the actual structure and the size of box is 8 bytes which is fixed. 

If this is right , can I raise a PR with the Fix ?

**Comment by Spoonbender** [comment]
I agree - this requires some adjustment. 

The size of a box on the stack is the size of a pointer (8 bytes on 64bit machines, 4 bytes on 32Bit machines etc.). 
The size of the boxed value on the heap isn't given by `mem::size_of_val(&boxed_value))` - that only provides the size of the box itself, since `&boxed_value` points at the box.

I think we could theoretically fix the heap sized reported by this example using `.as_ref()`:
```rust
// box size == pointer size
println!("Boxed point occupies {} bytes on the heap",
             mem::size_of_val(boxed_point.as_ref()));
println!("Boxed rectangle occupies {} bytes on the heap",
             mem::size_of_val(boxed_rectangle.as_ref()));
println!("Boxed box occupies {} bytes on the heap",
             mem::size_of_val(box_in_a_box.as_ref()));

// prints:
// Boxed point occupies 16 bytes on the heap
// Boxed rectangle occupies 32 bytes on the heap
// Boxed box occupies 8 bytes on the heap
```  

but - 
1. The comment `// box size == pointer size` does imply that this section should demonstrate the size of the Box (the pointer, not the pointed value) - so we probably want to demonstrate that, and just need to fix the text from "heap" to "stack" as you suggest
2. It could be misleading, given types that hold pointers to other values on the heap - since this technique only measures the size of the pointed value, not that of the entire graph.

So, IMO your proposal is good and you should issue a PR to fix the text.

**Comment by jon32446** [comment]
The code change was merged to master 21 days ago but the docs at https://doc.rust-lang.org/rust-by-example/std/box.html still show the old wording, "Boxed ... occupies {} bytes on the _heap_". Is this just a matter of waiting a little longer for it to reflect or is there some issue?

**Comment by marioidival** [comment]
@jon32446 yes, we have a problem... I just contact the infra team to fix that.
