### ISSUE TITLE
2.3: Arrays and Slices example comment is not correct

### ISSUE THREAD

**Issue by ysy** [rust-lang/rust-by-example#1654]
comment on line 53
 53: ` // Out of bound indexing causes compile error   `     
 54: `//println!("{}", xs[5]);`
Actually it dose not cause compile error, but a runtime panic of "index out of bounds" .

rsutc version: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**Comment by RicardoHS** [comment]
Just found this issue. I have created a PR #1743

**Comment by voodoojunk** [comment]
The slice comment on line 55 is also wrong. There's no runtime error if you uncomment line 56.
```
    //println!("{}", xs[..][5]);
```
There IS however a runtime error if you change the line to:
```println!("{}", &xs[5]);
```
Which is supposedly the same since passing a reference means passing a slice, but this also goes against lines 39, 40:
```
    assert_eq!(&empty_array, &[]);
    assert_eq!(&empty_array, &[][..]); // Same but more verbose
```
They are apparently not the same (unless I got it wrong)

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
