### ISSUE TITLE
Add a GitHub icon with a link to the repository

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust-by-example#337]
I think it would be nice if people could find an easy way to the repository to contribute.
Currently i don't see such a path.

There are already Twitter, Facebook, etc. icons in the top right corner. I suggest adding a GitHub icon linking to the repository.

**Comment by iKevinY** [comment]
I think changing the icon to a GitHub icon and moving it to the right side would make more sense conceptually, as that would leave site functionality on the left and externally-facing links on the right.

**Comment by steveklabnik** [comment]
I'd be happy to mentor anyone on this issue; I believe the Rust Cookbook does this, so investigating how and applying it here would make sense.

**Comment by budziq** [comment]
> I believe the Rust Cookbook does this

Yep. We have an "edit" button linked to github inline edit for given page source code.

**Comment by hardvain** [comment]
@steveklabnik  I believe this has to be changed in the mdbook repo.

**Comment by budziq** [comment]
> I believe this has to be changed in the mdbook repo.

mdBook is mostly a generic and not all books are interested in such mode of contribution (RBE and Cookbook might be atypical here). So such feature would have to be opt-in. On the other hand the mdbook is designed to be extended with custom css/js and page templates.

**Comment by hardvain** [comment]
@budziq I believe its not about the mode of contribution. These days almost all of the OSS libraries provide a github link in their websites and since mdbook is targeted towards easy book generation especially for OSS projects, adding a github link in mdbook's repo would still fit well. Even if it is not the case, my point in previous comment was that there is no source code changes required in this repository to fix this issue. Kindly correct me if I am wrong.

**Comment by budziq** [comment]
> Even if it is not the case, my point in previous comment was that there is no source code changes required in this repository to fix this issue. 

That is true enough, but please remember that RBE is not the only mdBook client and changing the default UI/UX affect them all. This is why such trivial change was made as a customization in cookbook repo rather than in mdbook itself or if we would like to provide such functionality I would suggest making it opt-in rather than default behaviour (while most not all mdbook clients are github/opensource/ or even source code oriented).

**Comment by hardvain** [comment]
@budziq Can you kindly point me to the mentioned change in cookbook repo? I am not aware of this. May be I can take that as a pointer and proceed.

**Comment by budziq** [comment]
> Can you kindly point me to the mentioned change in cookbook repo?

Sure [link](https://github.com/rust-lang-nursery/rust-cookbook/commit/fb85933a59ffdbb4d7be42cabee87a0e2a181cc2). I don't say its the ideal solution but it works for us ;)

**Comment by hardvain** [comment]
@budziq I was not aware of this extension mechanism. Thanks for the pointer. Here is the PR: https://github.com/rust-lang/rust-by-example/pull/911

**Comment by budziq** [comment]
hmm on the other hand we might think about adding some generic html/hbs include mechanism to mdbook to facilitate replacing just a part of index.hbs without need to pull all of it to your repo.

**Comment by hardvain** [comment]
Ya, duplicating the entire index.hbs just for a line change seems bad for me. Also now, we need to keep the index.hbs updated with the main repo to get new features.
