### ISSUE TITLE
Make examples which use tests runable in playpen

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#593]
Playpen now supports [tests](http://is.gd/Dh2YDF). Try moving the test examples to it.

**Comment by steveklabnik** [comment]
So, I expect this to Just Work, but it doesn't, try clicking run on https://rustbyexample.com/meta/test.html

I'm happy to mentor someone to help fix this!

**Comment by Zengor** [comment]
I was looking into this and it seems that the playground [does not currently support running tests when `main` is present.](https://play.rust-lang.org/help#features-tests) I was initially going to suggest rewriting the Tests chapter without the use of `main` as a way to work around the playground limitation. However, it got a bit more complicated when I looked at [section 15.4](https://rustbyexample.com/macros/dry.html), which does *not* feature main, but ends up getting a compilation error because of it. It won't even compile if I add `#![crate_type="lib"]` at the top. Note that the DRY section does work on the actual playground website, either with or without specifying the crate as `lib`

I'm not sure where to go from here as I don't fully understand how the playground works and how it's called (not sure how to look for this). I figure this is a bug with playground (or mdbook?) where the checks for whether to run `cargo build` or `cargo test` in place of `cargo run` are not being done at all.

**Comment by steveklabnik** [comment]
Interesting. Yeah, if it works on the playground but doesn't work with the play button, that's an mdbook bug.

**Comment by marioidival** [comment]
mdBook support tests, so this issue can be closed.

https://github.com/rust-lang/mdBook/issues/451#issuecomment-548453601
