### ISSUE TITLE
custom_types/enum: The first enum example is very complicated

### ISSUE THREAD

**Issue by mpe** [rust-lang/rust-by-example#601]
The enum example uses namespacing, boxes, and match, as well as talking about concrete types, references and borrowing, none of which has been introduced yet (@ 3.2).

I realise sometimes it's impossible to only use concepts which have already been introduced, but this seems like it could be simpler, or if not, moved later.

**Comment by mdinger** [comment]
Well, it definitely needs references at the bottom for all those topics at a minimum. `Box` should probably stay or move to a separate page of `enum`s because a linked list is usually created via an `enum`.

FWIW, I'm pretty sure it used to be much later in the tutorial which is why it has so many concepts in it. I'm definitely for simplifying examples.

How do you like the [destructuring/enums example](http://rustbyexample.com/flow_control/match/destructuring/destructure_enum.html) for comparison?

**Comment by mpe** [comment]
Moving it later would be best IMHO. Or drastically simplifying it, though I don't actually understand it well enough to say if that's even possible.

The destructuring/enums example is much better. That would be better at 3.2 I think, with a little more explanation in comments about what's going on.

**Comment by mpe** [comment]
Just another note, the example at 3.2.1 does a much better job of explaning the use syntax:

````
// If you'd like to refer to the days without saying
// `Day::Monday`, then you use the following notation
// use Day::{
//     Monday,
...
````

Whereas in the List example it looks at first glance as if you're use'ing List and Cons from somewhere else:

````
// Allow Cons and Nil to be referred to without namespacing
use List::{Cons, Nil};
````

**Comment by mdinger** [comment]
Well, the examples are no longer strictly in order because it's more direct to just link to simple explanations.

Regarding moving `enum` destructuring earlier, my preference is to explain destructuring in one general location so the span of what destructuring can do is more obvious. Adding simple examples to the `enum` section to elaborate on a specific point is something that could be done though.
