### ISSUE TITLE
Change Foreign Function Interface / Complex example

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust-by-example#643]
We have [no portable way (1)](https://github.com/rust-lang/rust/issues/10500#issue-22715435) [(2)](https://github.com/japaric/complex.rs/issues/6) to pass complex values in ffi, so we should use a different example for ffi. Current example is not portable (fails on 32-bit x86 for example).

**Comment by andresv** [comment]
One more example here: https://users.rust-lang.org/t/ffi-complex-math-does-not-work-on-32-bit-machine-with-rust-1-2/2714

**Comment by cmyr** [comment]
I'd be happy to take a stab at this, splitting the FFI into sections for 'calling into C' and 'exposing a C interface'. For the first example, maybe just calling out to `libcurl` and doing a simple http GET? Or something with `libgit2`? I'm very open to suggestions.

For the example going the other way (exposing a C interface) there's obviously a bit more flexibility. I would propose some example that involves returning an opaque pointer to some rust type, and then maybe calling some functions with string arguments and string return values, since those can be a bit tricky? But basically just trying to cover the things I've previously had to look up in the [ffi omnibus](http://jakegoulding.com/rust-ffi-omnibus/). 

Let me know if this would be helpful. =)

**Comment by marioidival** [comment]
Hi, I'm closing this issue just to clean up the items that already exist. If you think this issue makes sense to stay open, please create a new issue with updated information and mention this one.

thanks!
