### ISSUE TITLE
building on debian requires a symbolic link hack

### ISSUE THREAD

**Issue by hartsantler** [rust-lang/rust-by-example#644]
From the front page, to install on debian it says this command is required:
`sudo ln -s /usr/bin/nodejs /usr/bin/node`

I would rather not mess around with my system with symbolic links.  I am using LinuxMint, and it ships with a command `node` which is not NodeJS.  It is too bad different linux vendors have not standardized on the proper command line name for nodejs, but its simple to detect at runtime and use the correct one.

```python
## on fedora nodejs command is `node`, but on others it can be `nodejs`
nodejs_exe = 'node'
if os.path.isfile('/usr/sbin/ax25-node'):
	if os.path.isfile('/usr/sbin/node'):
		if os.path.realpath('/usr/sbin/node') == '/usr/sbin/ax25-node':
			nodejs_exe = 'nodejs'

```

**Comment by mdinger** [comment]
I'm not sure this will work because I don't think we call nodejs explicitly. We use gitbook and I think it calls nodejs. We just set it up so when it tries to use nodejs, it's available.

You can check yourself. This doesn't pull up anything aside from what's in node_modules:
```cmd
grep -r --exclude-dir=node_modules nodejs .
```

I'd check to see if gitbook works without the `ln` but it sorta seems like this should go [upstream](https://github.com/GitbookIO/gitbook)

**Comment by steveklabnik** [comment]
You can install the node-legacy package instead of the symlink.

**Comment by steveklabnik** [comment]
Since this is a combination of 'upstream issue' + 'fix available', I'm giving it a close.
