### ISSUE TITLE
Syntax highlighting highlights 'us' and 'is' suffixes (not 'usize' and 'isize')

### ISSUE THREAD

**Issue by Grazfather** [rust-lang/rust-by-example#662]
I noticed while playing around here: http://rustbyexample.com/cast/literals.html

> Numeric literals can be type annotated by adding the type as a suffix, with the exception of usize that uses the usize suffix and isize that uses the isize suffix.

Notice the weird wording? Well it had me try out both. `5isize` compiles, but `5is` has proper syntax highlighting.

**Comment by mdinger** [comment]
I'm pretty sure that used to work but I don't know when that suffix got backed out. Either way, it's not an issue with rustbyexample, it's a problem with [ace](https://github.com/ajaxorg/ace problem). I think it could be fixed by changing `us` and `is` to `usize` and `isize` [here](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/rust_highlight_rules.js#L129-L134) but I haven't tried it so it probably needs verification.

When did `is` and `us` get removed? I guess I don't remember it happening.

**Comment by Grazfather** [comment]
I'll report it on ace, then.

I am new to rust, so it was all new to me. Looks like it was done [this year](https://github.com/rust-lang/rust/issues/22496)

**Comment by mdinger** [comment]
He merged a fix into ace so rbe will pick it up once it makes it to [ace-builds](https://github.com/ajaxorg/ace-builds)

**Comment by Grazfather** [comment]
:+1:

**Comment by steveklabnik** [comment]
yup

**Comment by ubsan** [comment]
Triage: This has been fixed.
