### ISSUE TITLE
#[derive] attribute needs better documentation

### ISSUE THREAD

**Issue by keithamus** [rust-lang/rust-by-example#706]
Hi! I'm very new to Rust (but very enamoured by it)! I've been looking through code and watching screencasts, and it seems that the `#[derive]` attribute is very popular, but the documentation for it seems very limited.

Theres a [small paragraph in the book about derive](https://doc.rust-lang.org/book/traits.html#deriving), and [slightly more info in the reference](https://doc.rust-lang.org/reference.html#derive). it feels like the explanation is not in depth enough. I understand that it automatically implements traits for a struct, but that's about it. The questions I still have about it:
- What can I derive? Every built in trait, or only some (as the book implies)? If some, why those ones and not the others?
- How does it work? It seems to expand like a macro - at least this is implied by the reference.
- Can I make my own derives? If not why not? If so how?

**Comment by mdinger** [comment]
I think it is limited to the specific set of traits the book lists in that link. I'm not certain about the second but it might be like a macro. I'm fairly certain there was work in the past to bring macros and attributes closer together though I don't know the present state of it. Maybe someone else will comment to give you more info. Otherwise, you'd be well served to ask on IRC.

**Comment by steveklabnik** [comment]
Short answers:

1. You can only derive the list of traits listed. The reason why is due to different reasons for each trait that's not on the list.
2. It works through Compiler Magic (tm) right now. It does expand to code like a macro.
3. You cannot make your own because you cannot define your own attributes right now. Eventually, you will, on both fronts.

**Comment by steveklabnik** [comment]
(I do think that we need better docs on this, thanks for raising the issue)

**Comment by keithamus** [comment]
Thank you both for your answers :smile:.

**Comment by Seeker14491** [comment]
The `Copy` trait is also derivable, but it's missing from the list of derivable traits.

**Comment by Xmasreturns** [comment]
#763 should have addressed this, so I think this can be closed. Let me know if it's not!

**Comment by steveklabnik** [comment]
Closing, thanks @Xmasreturns !
