### ISSUE TITLE
Proposal: Remove 16.5.2 Combining separate combinators

### ISSUE THREAD

**Issue by Xmasreturns** [rust-lang/rust-by-example#764]
[16.5.2 Combining separate combinators:](http://rustbyexample.com/error/option_with_result/combinator_combinations.html)

This page serves only as an example of awkward code, which is then fixed in 16.5.3. Is there any particular reason it should stay around?

My suggestion is to remove 16.5.2 completely and add some text to the preferred 16.5.3 solution.

**Comment by mdinger** [comment]
Isn't it reasonable to use something awkward to motivate a better approach? I should think it is instructional to see what happens when [16.5.1](http://rustbyexample.com/error/option_with_result/result_string_errors.html) style is overused.

It could be argued that only good code ever appear in examples but in reality people learn as much from what not to do as from what to do. Do you disagree?

**Comment by Xmasreturns** [comment]
I think in the context of a blog post it could definitely make sense, but the current setup doesn't seem to fit in with the rest of RBE. The site *can* be read sequentially, but topics are written concisely and independently (mostly) so as to not require being read that way.

For any user that wants to skip around a bit in Ch16, having 3 sections essentially linked together is a mismatch with the length and accessibility of other topics.

**Comment by mdinger** [comment]
This somewhat seems reasonable but I'm not sure. I'd definitely be careful making big changes. I'll explain: someone reading this should see the combinators used to great extent up to the point of `try!` and then immediately see combinators return to use. The reason for this is that combinators have little reason to exist if the main and default manner for extracting and manipulating values inside `Results` is through `try!` (why as the reader did I just read multiple pages on combinators before I was introduced to `try!` when I'd always prefer `try!`?). Somehow the reader should notice they've become unbearable.

Therefore it seems necessary to highlight that in some cases, combinator chaining becomes awkward and infeasible to manage. In these cases, `try!` should be the more common tool. The added benefit of automatic error conversion is a nice benefit.

This wasn't to say you were intending to change this but when I was playing around with it for a bit, it was really easy for me to slip towards `try!` when the benefits of doing so from the examples standpoint was unclear.

---

The fact that the sections aren't independent is problematic but also tricky to handle. The [book section](https://doc.rust-lang.org/book/error-handling.html) this section was heavily based upon is in no way brief. This topic is complicated.

**Comment by Xmasreturns** [comment]
As it stands, the opening statement of 16.5 is:
"In the following sections, we will see how to combine separate operations returning Option and Result into a single operation that returns whichever one makes the most sense."

As a reader knowing of combinators and `try!`, I want to know:
* The benefits and drawbacks of using certain combinators
* The benefits and drawbacks of using `try!`
* Some specific use cases of each

At the moment, none of these are obvious to the reader, and a page of purposefully suboptimal code doesn't help. That being said, the topic is confusing even to me. If you have any suggestions for a "story" to tell throughout the error-handling chapter, it'd be very helpful for guidance while writing.

**Comment by mdinger** [comment]
Basically they can often be used interchangeably in most cases but a lot of it comes down to preference. I have a decided preference to use `try!` whereas some people with a strong functional programming background have a decide preference for combinators. `try!` introduces functional escapes which some people don't seem to like. I'm not sure the reason for this dislike. The fact that the combinators are often really subtly different where getting the correct one can be really picky is a strike against them in my eyes (the distinction between `map` and `and_then` is subtle and tricky).

Some facts:
* Both combinators and `try!` require the errors be mapped
* advantage: `try!` handles the mapping behind the scenes
* disadvantage: combinator usage requires more combinator usage
* advantage: `try!` removes the container and allows bare operations without combinators
* disadvantage: `try!` introduces escapes which people don't always like
* disadvantage: continued combinator usage nests deeper and deeper

Note: originally I was trying to strongly motivate combinators because I have a decided preference against using them; some people have a preference for them so I wanted to make sure they got a fair audition.

---

While thinking through this, I think what you could do is swap [this](https://is.gd/W8S4oF) into [16.5.3](http://rustbyexample.com/error/option_with_result/enter_try.html) and remove [16.5.2](http://rustbyexample.com/error/option_with_result/combinator_combinations.html) but the wording must change. Your motivation for using `try!` is to remove the extra nesting `and_then` requires (of course, this is entirely based on preference).

@steveklabnik Was there ever a proposal to have `and_then` automatically include `Err(From::from(err))`? I should think it could be argued that `and_then`/`map` be the recommended usage path when it is the last call in the function *if* errors are automatically converted. If not, `try!` is the recommended path.

**Comment by mdinger** [comment]
Also note that [trait based exceptions](https://github.com/rust-lang/rfcs/blob/master/text/0243-trait-based-exception-handling.md) landed on nightly I think and so it may land on stable in some form eventually. Not sure what the time frame is though.

**Comment by Xmasreturns** [comment]
After reading through more of the book and trying to rework the RBE chapter, I'm struggling to easily incorporate knowledge into RBE as currently structured. The book section does a great job of giving reason for individual choices, and I think there's a significant amount that can be removed for efficiency in RBE. Convenient, its sections "The limits of combinators", "Early returns", and "try!" mostly contain the reasonings I've been looking to add to RBE as well.

What do you think of this reordering, which is heavily based off of [the book](https://doc.rust-lang.org/book/error-handling.html):

16 - `panic!`
16.1 - `Option`
16.1.1 - Combinators: `map` (include link to [enum.Option](https://doc.rust-lang.org/std/option/enum.Option.html))
16.1.2 - Combinators: `and_then` (include link to [enum.Option](https://doc.rust-lang.org/std/option/enum.Option.html))
16.2 - `Result` (explain overlap of combinators and include link to [enum.Result](https://doc.rust-lang.org/std/result/enum.Result.html))
16.2.1 - aliases for `Result`
16.3 - Working with multiple error types (explain combined use of Option+Result)
16.3.1 - Using combinators (include all of `and_then`, `map`, `map_err`)
16.3.2 - Early returns (rewrite 16.3.1 using early returns)
16.3.3 - `try!` (acts like combinators, but includes control flow via early returns)
16.4 - Defining an error type
16.5 - Other uses of `try!`
16.6 - Re-enabling `Box`

This restructures the chapter into roughly the same number of sections and has clear parallels to the book. Having a similar structure allows for better accessibility of information if someone wants to read deeper into any given subject as well.

**Comment by mdinger** [comment]
Actually, I don't see that being very different from the current structuring aside from the titles being renamed and the numbering being different. I guess I don't have any big issues with it.

> Convenient, its sections "The limits of combinators", "Early returns", and "try!" mostly contain the reasonings I've been looking to add to RBE as well.

I don't get these statements. "The limits of combinators" is the same as [16.5.2](http://rustbyexample.com/error/option_with_result/combinator_combinations.html) except maybe he writes better. He gives a hairy example in order to highlight the fact that something cleaner is needed. What he doesn't do is explain why `try!` approach makes it so much cleaner comparatively. This was explained on rbe.

"Early returns" is the same as [16.5.3](http://rustbyexample.com/error/option_with_result/enter_try.html). It takes the other verbose combinator experiment, converts it to try, and showcases the improvement.

I'm not sure which `try!` section you're referring to but it probably is technically covered in section [16.7](http://rustbyexample.com/error/reenter_try.html). I think this was problematic because he provides excellent detail and reasoning but also requires a massive blog post length article to explain sections. I didn't think the length and detail was necessarily appropriate to the rbe format (if I could get away with it). The error handling section was already huge and each example very large (something the book version conveniently skips because it isn't runnable) because of the boilerplate each example requires. I felt certain the reduction of boilerplate alone would help to make the section more understandable.

---

Saying they're the same may not be fair. I didn't reread either sections today and rbe in general is more brief. The confusions you mentioned may also be that rbe is too brief. I'd have no way to know that though since this is the first pointed questioning about it's comprehensibility.

**Comment by Xmasreturns** [comment]
The RBE version of error handling is certainly shorter. After some rereading, I believe the confusion I ran into with RBE came from either page and chapter structure, or the way in which it was presented. The presentation can be partially fixed by giving labels more representative of content (e.g. where do I go to find combinators?).

Page structure refers to where I'm defining terminology and where it then gets used. My previous changes to the RBE chapter were based primarily edits, but here's a subset of things I didn't realize until I read the book chapter on error handling:
* `.map` and `.and_then` are both combinators
* the list of available combinators is different for `Option` and `Result`
* simple workflow methods to get into error handling

I think all of the above are important to know, and the information is mostly there in RBE. Unfortunately, it's not as easy to extract that information out of the RBE version yet. I'll see if I can't put in some work this week on this chapter, but things that I'd like to add: 
* more independence of sections from each other
* a workable definition of combinators
* improved ease of using reference links
* better distinction between "combinators" and `try!`

**Comment by mdinger** [comment]
I originally tried to come up with a definition of combinators but I think I eventually came up empty. The book uses them as if the definition is somewhat understood. Try this [link](http://stackoverflow.com/questions/93526/what-is-a-y-combinator). In short, it seems to be like this (I didn't read it all but I thought I got the gist of it (though, they said it's important for recursion reasons but I didn't look long enough to follow that part)):

```rust
let y = 3;
// A combinator must use all its arguments somehow, uses all of them and no others.

// Takes x as an argument and uses it.
let combinator = |x| x;

// Takes x as an argument and doesn't use it. Not a combinator.
let non_combinator = |x| 3;
// Additionally, uses a variable other than it's argument so not a combinator.
let non_combinator_2 = |x| y;

// Uses both and no others so a combinator.
let another_combinator = |x, y| x * y;

// Basically, it seems to be something which implies some type of very simple
// functionality which cannot be modified by external influences. But basically,
// it is the name for this category of tool.
```

I had the same issue with ADT's and sum types when covering enumerations. Actually, the closest I've seen to a good definition for ADT and sum types is probably [this](http://stupidpythonideas.blogspot.com/2014/08/adts-for-python.html) which I only came across recently.

---

Using more representative headers certainly seems reasonable. I'm curious to see what you achieve. I previously thought you'd be trying to remove the different example which appears in `16.5.2-3`; it being used to exemplify the deep nesting combinators may require.

I'm definitely interested in it becoming clearer so this sounds good.

**Comment by mdinger** [comment]
Also, when rbe ports to mdbook, we'll get [this](http://azerupi.github.io/mdBook/format/rust.html#Inserting%20runnable%20Rust%20files) which allows boilerplate and such to be hidden if we desire. I think it might be really useful in this section but I haven't tried it so I'm not sure. I thought editing was almost finished but it stagnated so I'm not sure how close he got to having it working.

**Comment by Xmasreturns** [comment]
Got a bit distracted with reworking Ch16, but I wanted to drop [this stackexchange link](http://programmers.stackexchange.com/questions/117522/what-are-combinators-and-how-are-they-applied-to-programming-projects-practica) off as a reference for anyone who might be interested in the topic of combinators. It's one of the more practical explanations I've found, and matches up easily with the implementation in Rust.

**Comment by mdinger** [comment]
Nice! BTW, you don't have to explain it all in detail in rbe even if the subject requires detail. Just write up a good explanation as a definition and submit a PR to the [rust glossary](http://doc.rust-lang.org/nightly/book/glossary.html). The book needs a good explanation of it as well since they utilize it heavily in the error handling section also. They could link to it as well.

**Comment by Xmasreturns** [comment]
I'm still slowly working on this. Just as an update, the structure currently looks like:

* 16 - Error handling
 * 16.1 - panic
 * 16.2 - Option & unwrap
   * 16.2.1 - Combinators: map (include link to enum.Option)
    * 16.2.2 - Combinators: and_then (include link to enum.Option)
 * 16.3 - Result (explain overlap of combinators and include link to enum.Result)
   * 16.3.1 - map for Result
    * 16.3.2 - aliases for Result
 * 16.4 - Working with multiple error types (explain combined use of Option+Result)
   * 16.4.1 - Using combinators (include all of and_then, map, map_err)
    * 16.4.2 - Early returns (rewrite 16.3.1 using early returns)
    * 16.4.3 - try! (acts like combinators, but includes control flow via early returns)
 * 16.5 - Defining an error type
  * 16.6 - Other uses of try!
   * 16.7 - Re-enabling Box

On the surface, it doesn't look too different, but I think once I'm done it should (hopefully) have a better flow to it. I'll be glad when I finally get some other eyes on it though.

**Comment by mdinger** [comment]
Nice. I'll be happy to look it over once you've got it ready.

**Comment by Xmasreturns** [comment]
Been super out of the loop lately, so late update once again. I think the last bit of work to do is the code portion of 16.4.1. I'm going off of the nice transition to https://doc.rust-lang.org/book/error-handling.html#early-returns as an example. 

Since I want to make sure the functionality is the same, could you help me by rewriting https://is.gd/lRSsn0 to have the same functionality, but instead use early returns? I'm not confident I'll keep it properly formatted.

**Comment by mdinger** [comment]
See https://is.gd/R4sNsa. The second way there is probably how I would do it. I mean, both work but at this point, the strings get in the way of early returns and nesting gets in the way of mapping. Both are awkward.

**Comment by Xmasreturns** [comment]
Thanks for the quick response! I apologize for getting to give some more context for the example. Right now the text beforehand looks like:

> In the previous example, we explicitly handled the errors using combinators. 
Another way to deal with this case analysis is to use a combination of 
`match` statements and *early returns*. 
That is, we can simply stop executing the function and return the error if 
one occurs. For some, this form of code can be easier to both read and 
write. Consider this version of the previous example, rewritten using early returns:

After the code example is some transitional text to the next section on `try!`, and I might move "Defining an error type" into 16.4 rather than splitting it off into 16.5.

I think I'm okay with having some awkwardness in the example here, as the chapter story is a bit clearer now. In essence, this example should show the functionality of combinators in another manner by rewriting them as match or if/return statements. What do you think?

**Comment by mdinger** [comment]
Oh, I misunderstood your request. Try this instead: https://is.gd/JwlLha . I would use the first over the second but neither is bad.

The example isn't as awkward now but it's definitely verbose. That isn't necessarily a problem though. I don't really think I have enough context to evaluate the example just from this.

BTW, the title for http://rustbyexample.com/error/reenabling_box.html might just be bad.  Originally I might have been thinking there was a preceding box example this was a follow up to but I couldn't find it.
