### ISSUE TITLE
8.2.2 Fn FnMut FnOnce text needs updating

### ISSUE THREAD

**Issue by alexandermerritt** [rust-lang/rust-by-example#770]
http://rustbyexample.com/fn/closures/input_parameters.html

~~Most of that is incorrect and~~ does not demonstrate how FnOnce executes once.

**Comment by mdinger** [comment]
If you wish anything to be fixed, you need to be very specific. As it is, this issue has provided nothing which is actionable and may never be fixed.

**Comment by steveklabnik** [comment]
Yes, I'm not sure what specifically is incorrect here.

**Comment by talchas** [comment]
The section

>   -  Fn: takes captures by reference (&T)
>   -  FnMut: takes captures by mutable reference (&mut T)
>   -  FnOnce: takes captures by value (T)

is very visible, and while it is corrected in the next paragraph, is still misleading - it certainly sounds like the default changes depending on the context's closure type, when it doesn't, and even the last line seems likely to further this confusion for thread::spawn's 'static bound.

The error messages (even in the example) expose this, though the more direct `apply(|| ...)` now gives a friendly error pointing at the move location if you change apply to Fn/FnMut.

Also if this section is about specifying closures as parameters it seems odd to never mention the limitations on the caller for each of these, since you generally want the most general you can manage. If this is about understanding API documentation/source that uses them this is less of a problem I guess?

Something like "can only take captures by reference (&T); can also take captures by mutable reference (&mut T)" would be clearer, IMO. I don't know how or where best to mention the closure caller's limitations.

**Comment by mdinger** [comment]
FWIW, this was based upon a [huonw blog post](http://huonw.github.io/blog/2015/05/finding-closure-in-rust). [This](http://huonw.github.io/blog/2015/05/finding-closure-in-rust/#structs-and-captures) might be a point fairly close to where he discusses things like this.

Why do you say it does not change based on context? The article I linked seemed to state that they are flexible in that fashion and this page attempted to reflect that sentiment. Have closures changed since that article was written to invalidate the article? I'm not sure what you're implying regarding `thread::spawn's 'static` bound. Could you clarify?

Noting the caller limitation and refining the wording both seem reasonable.

@Xmasreturns You're really good at making text read cleanly. Do you have ideas for this page? It looks to me like it could possibly be shorter by a bit but I haven't done more than just look at it. I wouldn't have time to play with it until the weekend I'm fairly sure.

**Comment by talchas** [comment]
That post explains it well - the closed over variables are captured based on how they are used in the closure, not what trait the closure needs to implement for the surrounding caller (and when the surrounding caller doesn't even exist sufficiently obviously, you don't even get error messages). Now to be fair, I don't believe there are many cases where capture /could/ change based on the Fn* requirement, but https://is.gd/1jBZKQ is one that in theory could have.

thread::spawn requires FnOnce + 'static, but this does not cause captures to be by value/move whenever possible, you have to explicitly write "move || ...". While inference about 'static and about the Fn* impls are different, people get confused initially already.

**Comment by mdinger** [comment]
Okay, I think I see the problem here but it's really subtle. I think rewording will take care.

Regarding `move`, it was covered 3 pages down. Avoiding it at that point was probably an explicit decision.

Also, I'm not really surprised about confusion though. It's all pretty complicated and tricky to explain in a perfectly clear and unambiguous way.

**Comment by Xmasreturns** [comment]
I took a crack at it. Hopefully the reordering and rewording help a bit. I also made a couple changes to the introduction in 8.2, since that felt lacking as a lead-up.

**Comment by alexandermerritt** [comment]
@Xmasreturns I like the rewording.

**Comment by ubsan** [comment]
Triage: fixed?

**Comment by mdinger** [comment]
Not quite. There's a PR but it hasn't merged yet.

@ubsan Thanks for triage!

**Comment by ubsan** [comment]
@mdinger ah, sorry, just trying to get rid of all the unnecessary issues :)
