### ISSUE TITLE
Add examples explaining different `use` syntax

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-by-example#803]
See https://github.com/rust-lang/rust-by-example/issues/801#issuecomment-250934593 for one problem of this type.

**Comment by steveklabnik** [comment]
It's not super clear right now what this ticket is about, could you elaborate, @mdinger ?

**Comment by rusty-snake** [comment]
Any progress here?

**Comment by marioidival** [comment]
No @rusty-snake , can you help us?

**Comment by rusty-snake** [comment]
@mdinger is talking about the following code sample:
```rust
fn main() {
    test_mod::foo();
}

mod test_mod {
    use Status::Poor;

	enum Status { Poor }

	pub fn foo() {
		let status = Poor;
	}
}
```
If you compile this code it will show a error **in Rust 2015**.
```
error[E0432]: unresolved import `Status`
 --> t.rs:6:9
  |
6 |     use Status::Poor;
  |         ^^^^^^ help: a similar path exists: `self::Status`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
```
In Rust 2018 (rustc >= 1.32) it will compile.

More informations: https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#use-paths

 I suggest to close since this affects only Rust 2015.

**Comment by marioidival** [comment]
@rusty-snake I agree!
