### ISSUE TITLE
std_misc/threads: contributing a more advanced threading example?

### ISSUE THREAD

**Issue by juleskers** [rust-lang/rust-by-example#859]
Hi everyone,

I stumbled over the [threads example][1], and while I think it is a good simple introduction, I felt it should be accompanied by a slightly more "powerful" or "involved" example.
For example, the current example doesn't use the Thread's return values in any way.

As an exercise for myself, I tried to come up with a second example, that shows some more challenging usage of threads. You can find it on the [integer32 playground][2] via [gist][3].

Before I go through the motions of re-formatting my plaything as a pull-request, I thought I'd ask here if there is interest in general, and if my example is "good enough".

I welcome improvements and (constructive) criticism. For example, I'm wondering if my example is too long, or if I'm muddying the waters too much by using lots of iterators.

[1]: http://rustbyexample.com/std_misc/threads.html
[2]: http://play.integer32.com/?gist=5b04c3351115496f025980ee896587a8&version=undefined
[3]: https://gist.github.com/anonymous/5b04c3351115496f025980ee896587a8

**Comment by mdinger** [comment]
I like the example a lot. It is certainly true the original example is bare but your example expanded it into an much more interesting direction. You could definitely add it as an example in the [testcase](http://rustbyexample.com/generics/phantom/testcase_units.html) style.

The fact that you used iterators is not necessarily a bad thing. People use different styles in practice and being exposed to them in documents such as this is instructive.

So, I would definitely consider it a good addition. You should definitely provide lots of links at the bottom of the example because a lot of the example may not be familiar to readers. I like it a lot!

**Comment by juleskers** [comment]
I'll try to make a test-case then.

Looking at other "test-cases", a "test-case" is simply a more involved example on the same topic, one that mimics "real usage" (a bit) more.

From the logistics side, if I understand everything correctly, I should 

- [ ]  create `examples/std_misc/threads/testcase_mapreduce/`
- [ ]  in there create `mapreduce.md` and `mapreduce.rs`
- [ ]  modify `examples/structure.json` to match, so that stuff actually gets included.
- [ ]  make a pull-request

Anything I'm missing?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust-by-example/pull/861 should have closed this!
