### ISSUE TITLE
Extend traits chapter

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust-by-example#90]
- [ ] supertraits `FooBar: Foo + Bar`
- [ ] trait objects `Box<Foo>`, `&Foo`
- [ ] "function overloading" using double dispatch: `Vec` \* `Vec` and `Vec` \* `int`

**Comment by Screwtapello** [comment]
Once you tell people that a struct can have implementations of any number of traits and the compiler will automatically look up which one to use, the immediate next question is "what happens when there's multiple traits with the same method?"

It would be helpful to have an example to point people to when they ask.

**Comment by steveklabnik** [comment]
Yup, all this would be great!

I'm happy to mentor anyone who wants to work on this issue.

**Comment by Morsicus** [comment]
I will be happy to help :)

**Comment by epage** [comment]
Another topic that would be useful for traits: comparing
1. generics (this might have impact on #913).
2. boxed traits
3. trait references

For trait references, I forgot I could even do this and had been using generics until my C++ mindset kicked in and realized it should work and [had to prove it to myself](https://play.rust-lang.org/?gist=f85ec3f398bd575d21c60527c105d0af&version=stable).
